# Generated by Django 2.1.5 on 2019-02-11 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('Title', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=1000)),
                ('Created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mentee',
            name='nickname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
