# Generated by Django 2.1.5 on 2019-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('bidang', models.TextField(max_length=50)),
                ('jadwal_praktek', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('Kandungan', models.TextField(max_length=255)),
                ('Khasiat', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('alamat', models.TextField(max_length=150)),
                ('keluhan', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('total_harga', models.CharField(max_length=100)),
                ('kumpulan_obat', models.TextField(max_length=150)),
            ],
        ),
    ]
